apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-net
spec:
  template:
    spec:
      containers:
        - name: weave
          env:
            - name: IPALLOC_RANGE
              value: "10.9.0.0/17"
        - name: weave-npc
          env:
            - name: IPALLOC_RANGE
              value: "10.9.0.0/17"